name: Build

on:
  push:
    branches:
    - py3
    - dan
jobs:
  build:
    runs-on:
      - bsonsearch-runner
      - focal
    steps:
      - uses: actions/checkout@v2
      - name: update system
        run:
          sudo apt-get update -y;
          sudo apt-get upgrade -y;
      - name: install c dependency
        run:
          sudo apt-get install -y tree libssl-dev openssl libtool flex autoconf automake ;
          sudo apt-get install -y libmagic1 libmagic-dev libpcre3-dev libpcre3 ;
          sudo apt-get install -y libstemmer0d libstemmer-dev libsodium-dev libaspell-dev aspell aspell-en;
          sudo apt-get install -y pkg-config uthash-dev libsodium23 libsodium-dev libprotobuf-c-dev libprotobuf-c1 duktape-dev libduktape205  duktape;
          sudo apt-get install -y wget cmake make build-essential;
          wget http://pkgs.bauman.space/discodb/sample.ddb -O /tmp/sample.ddb;
          wget http://pkgs.bauman.space/discodb/animals.ddb -O /tmp/animals.ddb;
          wget http://pkgs.bauman.space/discodb/cjk.ddb -O /tmp/cjk.ddb;
          wget http://pkgs.bauman.space/discodb/myths.ddb -O /tmp/myths.ddb;
          echo "don't have a yara, bson, or discodb installer for ubuntu, build from source and install";
          cwd=`pwd`;
          cd /tmp;
          tar -zxvf tar -zxvf duktape-2.7.0.tar.xz;
          cd duktape-2.7.0;
          make -f Makefile.sharedlibrary INSTALL_PREFIX=$(pwd)/../usr ;
          make -f Makefile.sharedlibrary INSTALL_PREFIX=$(pwd)/../usr install ;
          
          tar -zxvf cmph-2.0.2.tar.gz ;
          cd cmph-2.0.2;
          ./configure --prefix=$(pwd)/../usr --with-pic --with-spoon=SPOON;
          make
          make install
          tar -zxvf discodb-0.9.2.tar.gz;
          cd discodb-0.9.2;
          rm -rf cmake-release;
          mkdir cmake-release && cd cmake-release;
          sed -i '' $'10i\\\ninclude_directories(../usr/include/)\n' ../CMakeLists.txt
          sed -i '' $'10i\\\ninclude_directories(../usr/lib/)\n' ../CMakeLists.txt
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$(pwd)/../../usr -DCMAKE_REQUIRED_INCLUDES=$(pwd)/../../usr/include  ..;
          cmake --build .;
          cmake --install .; 
          ctest
          cd /tmp;
          rm -rf v4* ;
          wget https://github.com/VirusTotal/yara/archive/v4.0.5.tar.gz ;
          tar -zxvf v4.0.5.tar.gz ;
          cd yara-4.0.5 ;
          autoreconf -fiv ;
          ./configure --prefix=/usr/ --with-crypto --enable-magic;
          make;
          sudo make install;
          cd /tmp;
          rm -rf mongo-c-deiver* ;
          wget https://github.com/mongodb/mongo-c-driver/releases/download/1.17.4/mongo-c-driver-1.17.4.tar.gz ;
          tar -zxvf mongo-c-driver-1.17.4.tar.gz;
          cd mongo-c-driver-1.17.4;
          mkdir -p cmake-build;
          cd cmake-build;
          cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/../../usr -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DENABLE_TESTS=OFF -DCMAKE_BUILD_TYPE=Release ..;
          make;
          make install;
          cd ../../;
          tar -zxvf pcre-8.45.tar.gz ;
          cd pcre-8.45;
          ./configure --prefix=$(pwd)/../usr --enable-utf --enable-jit=auto --enable-pcre32 --enable-pcre16 --enable-pcre8 --disable-cpp --enable-newline-is-anycrlf --with-match-limit=100;
          make 
          make install 
          cd $cwd;
      - name: build release library
        run:
          rm -rf cmake-release;
          mkdir cmake-release && cd cmake-release;
          cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/usr -DCMAKE_BUILD_TYPE=Release .. ;
          cmake --build .;
          ctest; 
          cmake --install .;
      - name: install python dependency
        run:
          sudo apt-get install -y python3-pymongo python3-setuptools python3-dev python3-wheel python3-pip
      - name: build python library
        run:
          python3 setup.py build ;
          find . -name "*.so" | xargs -P1 -n1 ldd ;
