sudo: required

dist: bionic


language: c


install:
  - sudo apt-get install -y tree libpcre3-dev libpcre3 tree libbson-dev libbson-1.0-0 libstemmer0d libstemmer-dev libsodium-dev libaspell-dev aspell aspell-en libsodium23 uthash-dev libsodium-dev libyara3 libyara-dev



script:
  - sudo mkdir /usr/include/libbson-1.0/bson && cp /usr/include/libbson-1.0/*.h /usr/include/libbson-1.0/bson/.
  - cmake .
  - make
  - tree


