sudo: required

dist: bionic


language: c


install:
  - sudo apt-get install -y tree libpcre3-dev libpcre3 tree libbson-dev libbson-1.0-0 libstemmer0d libstemmer-dev libsodium-dev libaspell-dev aspell aspell-en libsodium23 uthash-dev libsodium-dev libyara3 libyara-dev
  - echo "pulling a test file so the test works"
  - wget http://pkgs.bauman.space/discodb/sample.ddb
  - wget http://pkgs.bauman.space/discodb/animals.ddb
  - wget http://pkgs.bauman.space/discodb/cjk.ddb
  - wget http://pkgs.bauman.space/discodb/myths.ddb
  - mv *.ddb /tmp/.
  - echo "don't have a discodb installer for ubuntu, build from source and install"
  - cwd=`pwd`
  - cd /tmp
  - git pull https://github.com/bauman/discodb.git
  - cd discodb
  - cmake .
  - make
  - sudo install libdiscodb.so /usr/lib/
  - sudo install src/*.h /usr/include/
  - cd $cwd


script:
  - echo "mongodb changed import paths in newer versions"
  - sudo mkdir /usr/include/libbson-1.0/bson
  - sudo cp /usr/include/libbson-1.0/*.h /usr/include/libbson-1.0/bson/.
  - cmake .
  - make
  - tree
  - echo "all the tests should exit 0 if they work"
  - ./bcon-sample
  - ./compare-equal
  - ./mongodbtests
  - ./compare-regex-equal
  - ./gte-compare
  - ./size-compare
  - ./near-compare
  - ./dt-compare
  - ./oid-compare
  - ./geonear-compare
  - ./compare-box
  - ./inset
  - ./yara-test
  - ./projection-test
  - ./unwind_compare
  - ./type-checking
  - ./exists-check
  - ./strlen-check
  - ./cryptcheck
  - ./textsearch
  - ./spellingsearch
  - ./geospace
  - ./ipaddrs
  - ./mathmodule
  - ./ethermodule
  - ./ipmodule
  - ./discomodule


