sudo: required

dist: bionic


language: c


install:
  - sudo apt-get install -y tree cmake libtool flex autoconf automake libpcre3-dev libpcre3 tree libbson-dev libbson-1.0-0 libstemmer0d libstemmer-dev libsodium-dev libaspell-dev aspell aspell-en libsodium23 uthash-dev libsodium-dev duktape-dev libduktape202  duktape
  - echo "pulling a test file so the test works"
  - wget http://pkgs.bauman.space/discodb/sample.ddb
  - wget http://pkgs.bauman.space/discodb/animals.ddb
  - wget http://pkgs.bauman.space/discodb/cjk.ddb
  - wget http://pkgs.bauman.space/discodb/myths.ddb
  - mv *.ddb /tmp/.
  - echo "don't have a yara, bson, or discodb installer for ubuntu, build from source and install"
  - cwd=`pwd`
  - cd /tmp
  - sudo apt-get install -y libcmph-dev libcmph0
  - wget https://github.com/bauman/discodb/archive/0.8.tar.gz
  - tar -zxvf 0.8.tar.gz
  - cd discodb-0.8
  - cmake .
  - make
  - sudo install libdiscodb.so /usr/lib/
  - sudo install src/*.h /usr/include/
  - cd $cwd
  - mkdir builddeps && cd builddeps
  - wget https://github.com/VirusTotal/yara/archive/v4.0.1.tar.gz
  - tar -zxvf v4.0.1.tar.gz
  - cd yara-4.0.1/
  - autoreconf -fiv
  -./configure --prefix=/usr/local --enable-magic
  - make
  - sudo make install
  - cd ..
  - https://github.com/mongodb/mongo-c-driver/releases/download/1.16.2/mongo-c-driver-1.16.2.tar.gz
  - tar -zxvf mongo-c-driver-1.16.2.tar.gz
  - cd mongo-c-driver-1.16.2
  - mkdir cmake-build & cd cmake-build
  - cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
  - make
  - sudo make install
  - cd $cwd



script:
  - echo "mongodb changed import paths in newer versions"
  - sudo mkdir /usr/include/libbson-1.0/bson
  - sudo cp /usr/include/libbson-1.0/*.h /usr/include/libbson-1.0/bson/.
  - cmake .
  - make
  - tree
  - echo "all the tests should exit 0 if they work"
  - ./bcon-sample
  - ./compare-equal
  - ./mongodbtests
  - ./compare-regex-equal
  - ./gte-compare
  - ./size-compare
  - ./near-compare
  - ./dt-compare
  - ./oid-compare
  - ./geonear-compare
  - ./compare-box
  - ./inset
  - ./yara-test
  - ./projection-test
  - ./unwind_compare
  - ./type-checking
  - ./exists-check
  - ./strlen-check
  - ./cryptcheck
  - ./textsearch
  - ./spellingsearch
  - ./geospace
  - ./ipaddrs
  - ./mathmodule
  - ./ethermodule
  - ./ipmodule
  - ./discomodule
  - ./samplingmodule
  - ./dukjs


